[package]
name = "destruct-cli"
version = "0.1.9"
edition = "2021"
repository = "https://github.com/Fake-User/Destruct-CLI.git"

[profile.release]
codegen-units = 1
strip = true
lto = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
tokio = {version = "1.44.1", features = ["full"]}
serde = { version = "1.0.219", features = ["derive"] }
tracing-subscriber = "0.3.19"
terminal_size = "0.4.2"
tracing = "0.1.41"
chrono = "0.4.40"
serde_json = "1.0.140"
s3sync = "1.12.3"
rand = "0.9.0"
dirs = "6.0.0"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.21.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
