Output destruct-cli.gif

Set Theme { "name": "Destruct", "black": "#000000", "red": "#ff0033", "green": "#ff0033", "yellow": "#ff0033", "blue": "#ff0033", "magenta": "#ff0033", "cyan": "#ff0033", "white": "#ffffff", "brightBlack": "#000000", "brightRed": "#ff0033", "brightGreen": "#ff0033", "brightYellow": "#ff0033", "brightBlue": "#ff0033", "brightMagenta": "#ff0033", "brightCyan": "#ff0033", "brightWhite": "#ffffff", "background": "#000000", "foreground": "#ffffff", "selection": "#ff0033", "cursor": "#ffffff", "prompt": "ffffff"}
Set FontSize 24
Set Padding 24
Set Height 850
Set Width 1500

Type "destruct-cli"
Sleep 2s
Enter
Sleep 2s

Type "sync"
Sleep 2s
Enter
Sleep 7s
